name: Gerar Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Obtendo a versão do arquivo .version
        id: version
        run: echo ::set-output name=version::$(cat .version)

      - name: Obtendo as mudanças correspondentes à versão atual
        id: changes
        run: |
          version=${{ steps.version.outputs.version }}
          changes=$(awk "/## $version/{flag=1; next}/##/{flag=0}flag" CHANGELOG.md)
          echo ::set-output name=changes::$changes

      - name: Criando uma nova release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          body: ${{ steps.changes.outputs.changes }}
          draft: false
          prerelease: false